// =============================================================================================
//
// ЗАПРОС ФОРМИРОВАНИЯ СПРАВОЧНИКА 'HandbookCorporation' 2-го ТИПА 
//
// версия rev.01 v01
// =============================================================================================

// ---------------------------------------------------------------------------------------------
// Запрос извлекает необходимые для работы столбцы из справочника 1-го типа и возвращает 
// сокращенный датасет для использования в прикладных таблицах.
// Запрос работает со справочником хранящим список корпораций, эти данные применяются в
// различных документов компании.
//
// источник:
//    TabCorporationList   - справочник 1-го типа
//
// возвращаемое значение:
//    table                - обработанный датасет - справочник 2-го типа
//
// ---------------------------------------------------------------------------------------------
let
    // извлечь объекты из файла-справочника
    sourceWorkbook = Excel.Workbook(Web.Contents(sourceWorkbook_TabCorporationList), null, true),

    // извлечь датасет из таблицы-справочника
    sourceTable = sourceWorkbook{[Item=sourceTable_TabCorporationList,Kind="Table"]}[Data],

    // задать типы данных столбцов которые будут возвращены в результирующем датасете
    setType = Table.TransformColumnTypes(    sourceTable,
                                            {
                                                {"IDnum", Int64.Type},
                                                {"CORPORATION", type text},
                                                {"FORM OWNERSHIP", type text}
                                            }),
    
    //удалить избыточные столбцы из результирующего датасета
    result = Table.RemoveColumns(    setType,
                                    {
                                        "COMMENT"
                                    })
in
    result