// =============================================================================================
//
// ЗАПРОС ФОРМИРОВАНИЯ СПРАВОЧНИКА 'HandbookUnits' 2-го ТИПА 
//
// версия rev.01 v01
// =============================================================================================

// ---------------------------------------------------------------------------------------------
// Запрос извлекает необходимые для работы столбцы из справочника 1-го типа и возвращает 
// сокращенный датасет для использования в прикладных таблицах.
// Запрос работает со справочником хранящим аббревиатуры единицы измерений применяемые в
// спецификациях и ТКП.
//
// источник:
//    TabUnits   - справочник 1-го типа
//
// возвращаемое значение:
//    table         - обработанный датасет - справочник 2-го типа
//
// ---------------------------------------------------------------------------------------------
let
    // извлечь объекты из файла-справочника
    sourceWorkbook = Excel.Workbook(Web.Contents(sourceWorkbook_TabUnits), null, true),
    // извлечь датасет из таблицы-справочника
    sourceTable = sourceWorkbook{[Item=sourceTable_TabUnits,Kind="Table"]}[Data],

    //удалить избыточные столбцы из результирующего датасета
    removeColumnTable = Table.RemoveColumns(   sourceTable, {"COMMENT"}),

    // откорректировать типы данных столбцов результирующего датасета
    result  = Table.TransformColumnTypes(   removeColumnTable,
                                            {{"IDnum", Int64.Type},
                                            { "UNITS", type text}})
in
    result