// =============================================================================================
//
// ЗАПРОС ФОРМИРОВАНИЯ СПРАВОЧНИКА 'HandbookBrand' 2-го ТИПА 
//
// версия rev.01 v01
// =============================================================================================

// ---------------------------------------------------------------------------------------------
// Запрос извлекает необходимые для работы столбцы из справочника 1-го типа и возвращает 
// сокращенный датасет для использования в прикладных таблицах.
// Запрос работает со справочником хранящим реестр производителей и брендов, эти данные применяются в
// спецификациях и ТКП.
//
// источник:
//    TabBrand  - справочник 1-го типа
//
// возвращаемое значение:
//    table     - обработанный датасет - справочник 2-го типа
//
// ---------------------------------------------------------------------------------------------
let
    // извлечь объекты из файла-справочника
    sourceWorkbook = Excel.Workbook(Web.Contents(sourceWorkbook_TabVendorAndBrand), null, true),
    // извлечь датасет из таблицы-справочника
    sourceTable = sourceWorkbook{[Item=sourceTable_TabVendorAndBrand,Kind="Table"]}[Data],

    //удалить избыточные столбцы из результирующего датасета
    removeColumnTable = Table.RemoveColumns(   sourceTable,
                                                {"IDnum",
                                                "VENDOR",
                                                "COUNTRY",
                                                "LINK",
                                                "COMMENT"}),

    // откорректировать типы данных столбцов результирующего датасета
    result = Table.TransformColumnTypes(  removeColumnTable,
                                          {{"IDvendor", Int64.Type},
                                          {"BRAND", type text}})
    
in
    result