>>> ПРОМТ <<<
//----------------------------------------------------------------------------------------------------------------------
ИСХОДНЫЕ ДАННЫЕ:
	В работе нашей компании используется много файлов шаблонов Excel в которые встроены запросы-утилиты 
	работающие в среде Power Query и которые приносят пользователям много пользы. Например у нас есть шаблон работы
	с коммерческими спецификациями, данный шаблон уже содержит запрос 'VendorAndBrand' который в прикладном файле спецификации
	формирует справочник второго типа (это такой справочник который подключается к фундаментальной таблице - справочнику
	первого типа, которая содержит основообразующую информацию которую менеджер проекта вводит в ручную, при этом справочник
	второго типа - это датасет он же таблица excel которая формируется из справочника первого типа путем выполнения power
	query запроса который 'вытягивает' из справочника первого типа сеченную по количеству столбцов справочную таблицу
	которая используется в прикладной спецификации как выпадающий список фиксированных значений и пользователю нужно лишь 
	выбрать из данного списка правильное значение). Справочник - 'VendorAndBrand' содержит информацию о вендорах с которыми мы
	работаем.
	Такие справочники второго типа позволяют сильно сэкономить время пользователю а также резко сокращают количество ошибок
	которые допускает пользователь при вводе значений.
	До текущего момента времени я разрабатывал запросы Power Query которые формируют справочники второго типа примерно так:
	``` TEXT
	let
    // извлечь объекты из файла-справочника
    sourceWorkbook = Excel.Workbook(Web.Contents(sourceWorkbook_TabVendorAndBrand), null, true),
    // извлечь датасет из таблицы-справочника
    sourceTable = sourceWorkbook{[Item=sourceTable_TabVendorAndBrand,Kind="Table"]}[Data],

    //удалить избыточные столбцы из результирующего датасета
    removeColumnTable = Table.RemoveColumns(   sourceTable,
                                                {"IDnum",
                                                "VENDOR",
                                                "COUNTRY",
                                                "LINK",
                                                "COMMENT"}),

    // откорректировать типы данных столбцов результирующего датасета
    result = Table.TransformColumnTypes(  removeColumnTable,
                                          {{"IDvendor", Int64.Type},
                                          {"BRAND", type text}})
    
	in
    	result
	```
	Здесь важно отметить что в запросе присутствуют такие аргументы как 'sourceWorkbook_TabVendorAndBrand' и
	'sourceTable_TabVendorAndBrand', при этом в теле запроса они нигде не объявлены.
	Работает это потому что такие аргументы объявлены в самом интерфейсе Powewr Query в разделе - 'Управление параметрами'
	Именно там создавались эти переменные и им присваивались требуемые значения.
	Но в таком подходе выявился серьезный недостаток,а именно мы несколько раз переносили расположение файлов - 
	справочников первого типа и получалось что переменная описанная в разделе Power Query - 'Управление параметрами'
	содержала недостоверную информацию, а так как у нас файлов шаблонов много а прикладных файлов выполненных на их основе
	еще в десятки раз больше то создалась неприемлемая ситуация - постоянно приходилось править значения аргументов 
	запросов в десятках файлов, что парализовало работу.
	
	Я принял решение, записать расположение всех таблиц справочников первого типа в одну Excel таблицу
	'TabTableList' которая хранится в Excel файле 'Таблицы-КБД список #2025.xlsx', который находится у всех
	пользователей по следующему адресу в файловой системе:
	'c:\OneDrive\01__LLC_MAS_2025\КИТ\01__КБД\03__Excel\TableList\'

	Сама таблица 'TabTableList' состоит из следующих столбцов:
	Данная таблица содержит следующие столбцы:
	'IDnum'			- содержит номер по порядку записи, столбец содержит набор уникальных значений,которые являются - целочисленными не повторяющимися, без разрывов значениями целых положительных чисел
	'TABLE NAME'		- имя таблицы - справочника первого типа
	'FILE NAME'		- имя файла в файловой системе компьютера который хранит Excel таблицу первого типа
	'isHANDBOOK'		- признак того - это справочная таблица или нет
	'PURPOSE TABLE'	- описание назначения таблицы
	'PATH'			- Путь к файлу таблице в файловой системе
	'COMMENT'			- Свободный комментарий к текущей записи в таблице

	теперь мне необходимо разработать Power Query запрос который будет использоваться внутри таких запросов как
	'VendorAndBrand', с целью избавиться от механизма хранения аргументов в Powewr Query в разделе - 
	'Управление параметрами'.
	Теперь во всех существующих запросах аналогичных - 'VendorAndBrand' параметр - 'sourceTable_TabVendorAndBrand'
	будет заменен на - 'sourceTable'  и его значение я буду 'жестко' задавать на этапе написания 'M' кода запроса
	запроса аналогичного 'VendorAndBrand' и ему подобным.
	А параметр 'sourceWorkbook_TabVendorAndBrand' будет переименован в - 'sourceWorkbook',
	и вот он автоматически возвращаться новым разрабатываемым запросом внутри таких запросов как 'VendorAndBrand' и ему
	подобным.
	Предстоит разработать описанный новый запрос.
	Название нового утилитарного запроса: 'UtilsGetPathTable'
	Он должен принимать один аргумент: '_sourceTable' - это имя таблицы справочника, запись о которой есть в таблице -
	'TabTableList'.
	По данному текстовому значению запрос 'UtilsGetPathTable' должен извлечь две компоненты пути к excel файлу 
	хранящему данную справочную таблицу. Это логика запроса должна выполнить следующим образом:
	 - найти строку в таблице 'TabTableList' которая в столбце 'TABLE NAME' содержит значение имени таблицы переданное
	 в запрос 'UtilsGetPathTable' через аргумент '_sourceTable';
	 - после того как будет найдена строка со значением таблицы, алгоритму необходимо восстановить полный путь к файлу 
	 Excel который хранит искомую таблицу-справочник первого типа. Это можно сделать путем конкатенации значений хранящихся
	 в найденной строке в столбцах 'PATH' и 'FILE NAME'	(именно в таком порядке требуется конкатенация);
	 - полученное значение вернуть в запрос аналогичный 'VendorAndBrand' т.е. тот который вызвал 'UtilsGetPathTable'.
	 После того как буден разработан и протестирован 'UtilsGetPathTable', мы приступим к коррекции всех запросов типа
	 'VendorAndBrand'.
	 Важные вводные при проектировании запроса 'UtilsGetPathTable' и всех последующих которые мы будем здесь разрабатывать:
	  - ты должна строго соблюдать стилистику моего написания 'M' кода всех здесь разрабатываемых модулей Power Query.
	  Для этого я приложу файлы с примерами моего кода который уже разработан. Тебе предстоит внимательно изучить приложенные 
	  примеры и следовать стилю написания кода;
	  - перед началом любого модуля, функции и т.д. Power Query на языке 'M' ты обязана делать качественный блок комментария
	  который содержит назначения модуля, функции и т.д. Описание сигнатуры с указанием всех входных аргументов, всех
	  возвращаемых значений, с обязательным указанием назначения аргумента и его типа а также типа возвращаемого значения.
	  - комментировать все значимые  этапы вычислений и логики модуля, функции и т.п. Power Query которые мы будем разрабатывать
	
	В качестве примера оформления кода я приложу код ETL процессора 'ProcessingTable', который мы с тобой ранее разработали
	в другом чате платформы 'Google AI Studio', а также приложу другие утилитарные запросы которые мы также с тобой ранее
	разработали в других чатах платформы 'Google AI Studio'.
	
	Приложенные файлы:
	1. 'UtilsFunctionVector rev.08 v04.txt';
	2. 'ProcessingTable rev.04 v01.txt'

ЗАДАЧА:
	Разработать утилитарный модуль-запрос Power Query - 'UtilsGetPathTable' назначение которого, используя текстовое значение
	имени справочной таблицы переданной в запрос через аргумент '_sourceTable', вернуть вернуть полный путь к Excel файлу который
	который содержит данную таблицу. Код и логика запроса должны жестко учитывать:
	- список всех путей всех искомых таблиц находится в Excel файле 'Таблицы-КБД список #2025.xlsx';
	- путь к файлу 'Таблицы-КБД список #2025.xlsx' - 'c:\OneDrive\01__LLC_MAS_2025\КИТ\01__КБД\03__Excel\TableList\';
	- таблица которая содержит пути всех искомых таблиц находится в файле 'Таблицы-КБД список #2025.xlsx' и имеет имя - 'TabTableList';
	Как можно сформировать полный путь к искомой таблице, было описано выше в данном промте.


РЕЗУЛЬТАТ:
	Вернуть полный, код запроса 'UtilsGetPathTable', с соблюдением требований 	к оформлению кода, комментариев и стиля
	которые описаны и и утверждены в данном чате.
	Присвоить коду запроса 'UtilsGetPathTable'  следующую ревизию и версию: 'rev.01' 'v01'

>>> ПРОМТ <<<
//----------------------------------------------------------------------------------------------------------------------
ИСХОДНЫЕ ДАННЫЕ:
	Мне нужны ответы по тому как работает логика  кода запроса 'UtilsGetPathTable'. Вот что меня интересует:
	- выполняется ли проверка того что в таблице 'TabTableList' существует запись имени таблицы которую
	передали в аргументе запроса - '_sourceTable' ? Такая проверка должна быть обязательна и если дает отрицательный
	результат, 	код запроса должен выдать пользователю сообщение об ошибке, которое четко поясняет что 	в таблице
	'TabTableList' не найдена запись с именем и далее подставить имя переданное в '_sourceTable';
	- проверяет ли код запроса что у найденной записи с именем переданным в '_sourceTable' в столбце 'FILE NAME'
	пустое 	значение? Такая проверка обязательно должна быть и если она дает отрицательный результат, то код 
	запроса должен выдать пользователю сообщение об ошибке, которое четко поясняет что в столбце 'FILE NAME'
	отсутствует имя файла;
	- проверяет ли код запроса что у найденной записи с именем переданным в '_sourceTable' в столбце 'PATH'
	пустое 	значение? Такая проверка обязательно должна быть и если она дает отрицательный результат, то код 
	запроса должен выдать пользователю сообщение об ошибке, которое четко поясняет что в столбце 'PATH'
	отсутствует путь к файлу;

ЗАДАЧА:
	1. Дать ответы на заданные вопросы в отношении проверок в коде запроса 'UtilsGetPathTable';
	2. Откорректировать код запроса 'UtilsGetPathTable' если в результате проверки выясниться 
	что онт не выполнял требуемых проверок. Четко прокомментировать каждый блок проверки;

РЕЗУЛЬТАТ:
	1. Дать развернутый отчет по вопросам заданным в данном промте;
	2. Если в результате проверки потребовалась корректировка кода, то вернуть полный код запроса
	'UtilsGetPathTable', с соблюдением требований 	к оформлению кода, комментариев и стиля
	которые описаны и и утверждены в данном чате.
	Присвоить коду запроса 'UtilsGetPathTable'  следующую ревизию и версию: 'rev.01' 'v01'
