/*
<QuerySpecResultNoImage>
Данный запрос является объединяющим, в результате которого происходит слияние 
данные текущей рабочей спецификации work из таблицы TableSpecificationAll и запроса
QuerySpecificationCustomer. В результате появляется спецификация в которой внесены
новые требования заказчика (плученные от него и хранящиеся в спецификации SpecificationCustomer),
но при этом в этой полученной спецификации отсутствуют данные о изображении номенклатуры из
спецификации, эти данные получаются отдельными операциями над спецификациями.
*/
let
    Источник = Table.NestedJoin(QuerySpecificationAll, {"АРТИКУЛ МАС"}, QuerySpecificationCustomer, {"АРТИКУЛ МАС"}, "QuerySpecificationCustomer", JoinKind.LeftOuter),
    #"Развернутый элемент QuerySpecificationCustomer" = Table.ExpandTableColumn(Источник, "QuerySpecificationCustomer", {"On-Off", "ПРИМЕЧАНИЕ"}, {"On-Off", "ПРИМЕЧАНИЕ"}),
    #"Переупорядоченные столбцы" = Table.ReorderColumns(#"Развернутый элемент QuerySpecificationCustomer",{"№ п/п", "№ ИСХ", "№ КОМПЛЕКТА", "№ ПОРЯДКОВЫЙ НОМЕР В КОМПЛЕКТЕ", "№ ПОЛНЫЙ", "ОПИСАНИЕ КОМПЛЕКТА", "НАИМЕНОВАНИЕ", "ОПИСАНИЕ/ХАРАКТЕРИСТИКИ", "On-Off","БРЕНД", "ПОСТАВЩИК", "АРТИКУЛ ПОСТАВЩИК", "АРТИКУЛ МАС", "МЕТОД РАСЧЕТА", "ЕД ИЗМ", "КОЛИЧЕСТВО В КОМПЛЕКТЕ", "КОМПЛЕКТОВ В ПОСТАВКЕ", "КОЛИЧЕСТВО ИТОГО", "КОЛИЧЕСТВО У ПОСТАВ-КА", "ЦЕНА ЗА ЕД. $ЗАКУП", "СЕБЕСТОИМОСТЬ $ЗАКУП", "КОЭФФ ПРОПОРЦИО-ТИ", "КОЭФФИЦИЕНТ НАЦЕНКИ", "ЦЕНА ЗА ЕД. $РЕАЛИЗАЦИЯ", "СТОИМОСТЬ $РЕАЛИЗАЦИЯ",  "ЦЕНА ЗА ЕД. $ИТОГ", "СТОИМОСТЬ $ИТОГ", "ТРЕБОВАНИЯ ИСХОДНЫЕ", "ПРИМЕЧАНИЕ", "ССЫЛКА"})
in
    #"Переупорядоченные столбцы"